---
- name: Deploy OpenVPN server using Docker
  hosts: all
  become: yes

  vars:
    openvpn_data: "/etc/openvpn"  # Define the OpenVPN data directory
    openvpn_port: "1194"  # Define the OpenVPN port
    openvpn_protocol: "udp"  # Define the OpenVPN protocol
    openvpn_domain: "{{ openvpn_domain }}"
  
  tasks:
    - name: Install general prerequisites
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python3
          - python3-pip
        update_cache: yes

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker Engine
      apt:
        name: docker-ce
        update_cache: yes
        state: latest

    - name: Ensure Python Docker SDK is installed
      pip:
        name: docker
        state: present


    - name: Ensure OpenVPN data directory exists
      file:
        path: "{{ openvpn_data }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Pull OpenVPN Docker image
      docker_image:
        name: kylemanna/openvpn
        source: pull
        
    - name: Generate OpenVPN configuration
      command: docker run -v {{ openvpn_data }}:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://{{openvpn_domain}}

    - name: Initialize OpenVPN PKI
      expect:
        command: docker run -v /etc/openvpn:/etc/openvpn --rm -it kylemanna/openvpn ovpn_initpki
        responses:
          'Enter New CA Key Passphrase:': 'YourSecurePassphrase'
          'Re-Enter New CA Key Passphrase:': 'YourSecurePassphrase'
          'Enter pass phrase for.*:': 'YourSecurePassphrase'
          'Common Name.*:':  '{{openvpn_domain}}'
      no_log: false
      

    - name: Create and start OpenVPN container
      docker_container:
        name: openvpn-server
        image: kylemanna/openvpn
        state: started
        restart_policy: always
        privileged: true
        ports:
          - "{{ openvpn_port }}:{{ openvpn_port }}/{{ openvpn_protocol }}"
        volumes:
          - "{{ openvpn_data }}:/etc/openvpn"
        sysctls:
          net.ipv6.conf.all.disable_ipv6: "0"
          net.ipv6.conf.default.forwarding: "1"
          net.ipv6.conf.all.forwarding: "1"

    - name: Initialize OpenVPN configuration
      command: docker run -v {{ openvpn_data }}:/etc/openvpn --rm kylemanna/openvpn ovpn_genconfig -u udp://{{openvpn_domain}}
      args:
        creates: "{{ openvpn_data }}/openvpn.conf"





    - name: Retrieve OpenVPN server information
      debug:
        msg: "OpenVPN server is running. Connect to it on port {{ openvpn_port }} over {{ openvpn_protocol }}."
